import images from '../constants/images';
import icons from '../constants/icons';

const UserCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
];

const BusLocationCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
];

const PersonPymentCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Paid',
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1580,
    status: 'Paid',
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Reject',
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1800,
    status: 'Paid',
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Paid',
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 2500,
    status: 'Reject',
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Paid',
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Paid',
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driverid: 'JH02AC 5649',
    image: images.person,
    rupee: 1500,
    status: 'Paid',
  },
];

export default {
  UserCartdata,
  BusLocationCartdata,
  PersonPymentCartdata,
};
